on:
  push:
    branches:
      - main
      - master

name: pkgdown

jobs:
  pkgdown:
      runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      BLS_KEY: ${{ secrets.BLS_KEY }}
      CENSUS_API_KEY: ${{ secrets.CENSUS_API_KEY }}
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v1

      - uses: r-lib/actions/setup-pandoc@v1

      - name: Install spatial libraries
        run: |
          # copied from sf github
          #  brew install pkg-config
          #  brew install gdal
          apt-get update -qq \
            && apt-get install -y gdal-bin \
            pkg-config 

      - name: Query dependencies
        run: |
          install.packages(c("renv", "devtools", "pkgdown"), type = "binary")
          renv::restore()
        shell: Rscript {0}

      - name: Cache R packages
        uses: actions/cache@v2
        with:
          path: $HOME/.local/share/renv
          key: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-${{ hashFiles('.github/depends.Rds') }}
          restore-keys: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-

      - name: Install package
        run: |
          devtools::install(upgrade = FALSE)
        shell: Rscript {0}

      - name: Check package
        run: devtools::check(error_on = "error", cran = FALSE)
        shell: Rscript {0}

      - name: Deploy package
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          Rscript -e 'pkgdown::deploy_to_branch(new_process = FALSE, lazy = FALSE)'
