on:
  push:
    branches:
      - main
      - master

name: pkgdown

jobs:
  pkgdown:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      BLS_KEY: ${{ secrets.BLS_KEY }}
      CENSUS_API_KEY: ${{ secrets.CENSUS_API_KEY }}
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v1
        with:
          r-version: '4.0.5'

      - uses: r-lib/actions/setup-pandoc@v1

      - name: Install libraries
        run: |
          sudo apt install -y gdal-bin \
            pkg-config \
            libcurl4-openssl-dev \
            libssl-dev \
            libicu-dev \
            imagemagick \
            libmagick++-dev \
            gsfonts \
            libxml2-dev \
            libudunits2-dev \
            libgdal-dev \
            gdal-bin \
            libgeos-dev \
            libproj-dev \
            pandoc \
            libfreetype6-dev \
            libpng-dev \
            zlib1g-dev \
            libharfbuzz-dev \
            libfribidi-dev

      - name: Cache R packages
        uses: actions/cache@v2
        with:
          path: $HOME/.local/share/renv
          key: r-${{ hashFiles('renv.lock') }}
          restore-keys: r-

      - name: Install dependencies
        run: |
          install.packages(c("renv", "devtools", "pkgdown"))
          renv::restore(repos = list(CRAN = "https://packagemanager.rstudio.com/cran/__linux__/focal/latest"))
        shell: Rscript {0}

      - name: Install package
        run: |
          devtools::install(upgrade = FALSE)
        shell: Rscript {0}

      - name: Check package
        run: devtools::check(error_on = "error", cran = FALSE)
        shell: Rscript {0}

      - name: Deploy package
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          Rscript -e 'pkgdown::deploy_to_branch(new_process = FALSE, lazy = FALSE)'
